# Generated by Django 5.0.1 on 2024-01-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='status',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
