# Generated by Django 5.0.1 on 2024-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_desafio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
